language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

addons:
  hosts:
    - wordpress-project.localhost

services:
  - mysql

before_install:
  - if [[ $TRAVIS_PHP_VERSION = 5.6 ]]; then export COMPOSER_MEMORY_LIMIT=-1; fi;
  - mysql -uroot -e "create database if not exists travis_test"

install:
  - composer install

script:
  - cd $TRAVIS_BUILD_DIR/web
  - ./../bin/wp config create --dbname=travis_test --dbuser=root --dbpass="" --dbhost=127.0.0.1
  - ./../bin/wp core install --url=wordpress-project.localhost --title="Composer Template for WordPress Projects" --admin_user=admin --admin_password=admin --admin_email=admin@wordpress-project.localhost
